In [26]:
import numpy as np


In [33]:
# User inputs the initial state and displaying the initial and goal states

i_state = list(map(int, input("Enter the initial state you want for the puzzle, seperated by space").split()))
init_state = np.array(i_state).reshape(3, 3) 
print("The initial state is: \n", init_state)
goal_state = ([1,2,3], 
              [4,5,6], 
              [7,8,0])
print("The goal state is: \n", np.array(goal_state).reshape(3,3))

'''# Check if the puzzle is solvable
def check_if_solvable(puz):
    for i in range(9):
        for j in range(i+1,9):
            if(puz[j] and puz[i] and puz[i] > puz[j]):
                count += 1
    return count
# Call the function and then perform the below steps

if (count%2 == 0):
    print("This is solvable")
else:
    print("This is not solvable")'''

# Search for the blank space/zero location in the matrix
def pos_of_zero(pos0):
    pos0 = np.argwhere(init_state == 0)
    print(" The position of 0 in the initial state of the puzzle is ")
    i = pos0[0][0]
    j = pos0[0][1]
    return pos0
#print(pos_of_zero(pos0))

# Function to move the blank space/zero by one space right
def swap(init_state, i, j):
    if (j != 2):
        temp = init_state[i][j]
        init_state[i][j] = init_state[i][j+1]
        init_state[i][j+1] = temp
        return init_state
    #print(swap(init_state, i, j))
    
# Function to move the blank space/zero by one space left
def swap(init_state, i, j):
    if (j != 0):
        temp = init_state[i][j]
        init_state[i][j] = init_state[i][j-1]
        init_state[i][j-1] = temp
        return init_state
    #print(swap(init_state, i, j))
    
# Function to move the blank space/zero by one space up
def swap(init_state, i, j):
    if (i != 0):
        temp = init_state[i][j]
        init_state[i][j] = init_state[i-1][j]
        init_state[i-1][j] = temp
        return init_state
    #print(swap(init_state, i, j))

# Function to move the blank space/zero by one space down
def swap(init_state, i, j):
    if (i != 2):
        temp = init_state[i][j]
        init_state[i][j] = init_state[i+1][j]
        init_state[i+1][j] = temp
        return init_state
    #print(swap(init_state, i, j))

Enter the initial state you want for the puzzle, seperated by space1 0 4 2 3 7 5 6 8
The initial state is: 
 [[1 0 4]
 [2 3 7]
 [5 6 8]]
The goal state is: 
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
