In [399]:
import numpy as np
import copy
count = 0

In [417]:
''' User inputs the initial state and displaying the initial and goal states. Also initializing all the variables used in
    various parts of the code '''

i_state = list(map(int, input("Enter the initial state you want for the puzzle, seperated by space").split()))
init_state = np.array(i_state).reshape(3, 3) 
print("The initial state is: \n", init_state)

goal_state = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,0]])
print("The goal state is: \n", np.array(goal_state).reshape(3,3))

parent_node = []
all_nodes = []
list.append(all_nodes, init_state)
list.append(parent_node, 0)
left = np.array([[0,0,0], [0,0,0], [0,0,0]])
right = np.array([[0,0,0], [0,0,0], [0,0,0]])
up = np.array([[0,0,0], [0,0,0], [0,0,0]])
down = np.array([[0,0,0], [0,0,0], [0,0,0]])
p = 0

Enter the initial state you want for the puzzle, seperated by space1 0 3 2 4 5 6 7 8
The initial state is: 
 [[1 0 3]
 [2 4 5]
 [6 7 8]]
The goal state is: 
 [[1 2 3]
 [4 5 6]
 [7 8 0]]


In [418]:
# Check if the puzzle is solvable
def check_if_solvable(puzzle):
    for i in range(9):
        for j in range(i+1,9):
            if(puz[j] > puz[i]):
                count += 1
    return count
# Call the function and then perform the below steps

if (count%2 == 0):
    print("This is solvable")
else:
    print("This is not solvable")

This is solvable


In [401]:
# Search for the blank space/zero location in the matrix

def pos_of_zero(pos0):
    pos0 = np.argwhere(pos0 == 0)
    i = pos0[0][0]
    j = pos0[0][1]
    #print(" The position of 0 in the initial state of the puzzle is ", i,j)
    return i,j



In [402]:
# Function to move the blank space/zero by one space right

def swap_right(state, row, col):
    init_state_copy = copy.copy(state)
    if (col != 2):
        temp = init_state_copy[row][col]
        init_state_copy[row][col] = init_state_copy[row][col+1]
        init_state_copy[row][col+1] = temp
        return init_state_copy
    else:
        return state


In [403]:
# Function to move the blank space/zero by one space left

def swap_left(state, row, col):
    init_state_copy = copy.copy(state)
    if (col != 0):
        temp = init_state_copy[row][col]
        init_state_copy[row][col] = init_state_copy[row][col-1]
        init_state_copy[row][col-1] = temp
        return init_state_copy
    else:
        return state


In [404]:
# Function to move the blank space/zero by one space up

def swap_up(state, row, col):
    init_state_copy = copy.copy(state)
    if (row != 0):
        temp = init_state_copy[row][col]
        init_state_copy[row][col] = init_state_copy[row-1][col]
        init_state_copy[row-1][col] = temp
        return init_state_copy
    else:
        return state



In [405]:
# Function to move the blank space/zero by one space down

def swap_down(state, row, col):
    init_state_copy = copy.copy(state)
    if (row != 2):
        temp = init_state_copy[row][col]
        init_state_copy[row][col] = init_state_copy[row+1][col]
        init_state_copy[row+1][col] = temp
        return init_state_copy
    else:
        return state


In [406]:
# Function to call all the above functions to make the necessary movements

def movements(new_node):
    #parent_node[p+1] = count
    #print("in")
    a,b = pos_of_zero(new_node)
    #print(a,b)
    
    global count
    count += 1
    
    left = swap_left(new_node, a, b)
    #print(left)
    unique_append(left)
    
    up = swap_up(new_node, a, b)
    #print(up)
    unique_append(up)
    
    right = swap_right(new_node, a, b)
    #print(right)
    unique_append(right)

    down = swap_down(new_node, a, b)
    #print(down)
    unique_append(down)
    return left,up,right,down

In [407]:
# Function to check if the new nodes are unique and append them to the all nodes array

def unique_append(current_node):
    global all_nodes
    global p
    global delete
    #print("Yes")
    uni = True
    for mat in all_nodes:
        if np.array_equal(mat, current_node):
            uni = False
    if (uni == True):
        list.append(parent_node, count)
        list.append(all_nodes, current_node)

In [408]:
# Code snippet to solve the puzzle and obtain the goal state

n =0
while(not((right == goal_state).all() or (left == goal_state).all() or (up == goal_state).all() or (down == goal_state).all())):
    left,up,right,down = movements(all_nodes[n])
    n = n+1

In [409]:
# Code Snippet for backtracking the obtained goal state to determine the path

size = len(all_nodes)
gs_i = size - 1
is_i = 1
path = []
index = 0

path.append(gs_i)
while (gs_i != is_i):
    path.append(parent_node[gs_i])
    gs_i = path[index]
    index += 1
    
path.sort()

In [410]:
# Code snippet to find the element in the path

for element in path:
    print(all_nodes[element])

[[0 1 3]
 [4 2 5]
 [7 8 6]]
[[0 1 3]
 [4 2 5]
 [7 8 6]]
[[1 3 0]
 [4 2 5]
 [7 8 6]]
[[1 3 0]
 [4 2 5]
 [7 8 6]]
[[4 1 3]
 [0 2 5]
 [7 8 6]]
[[4 1 3]
 [0 2 5]
 [7 8 6]]
[[1 2 3]
 [4 8 5]
 [7 0 6]]
[[1 2 3]
 [4 8 5]
 [7 0 6]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
